### ISSUE TITLE
CopySummGAT.py init parameter not match

### ISSUE THREAD

**Issue by yuezhao-zy** [luyang-huang96/GraphAugmentedSum#1]
in class CopySummParagraph(CopySummGAT):

`        # super().__init__(vocab_size, emb_dim,
        #          n_hidden, bidirectional, n_layer, side_dim, dropout, gat_args,
        #          adj_type, mask_type, pe, feed_gold,
        #          graph_layer_num, copy_from_node, copy_bank, feature_banks, bert, bert_length)
`
with error, it doesn't match the parameter of CopySummGAT.so I delete pe
`super().__init__(vocab_size=vocab_size, emb_dim=emb_dim,
                         n_hidden=n_hidden, bidirectional=bidirectional, n_layer=n_layer, side_dim=side_dim,
                         dropout=dropout, gat_args=gat_args,
                         adj_type=adj_type, mask_type=mask_type, feed_gold=feed_gold,
                         graph_layer_num=graph_layer_num, copy_from_node=copy_from_node, copy_bank=copy_bank,
                         feature_banks=feature_banks, bert=bert, bert_length=bert_length)
`

besides, does the code implement the function of copy_from_node? because when I set copy_from_node=True,  error happend.
`
        if self._copy_from_node:
            print("ext info:",ext_info)
            ext_node_words, ext_node_reps, all_node_mask = ext_info
            query_copy = torch.matmul(lstm_out, self._attn_copyh)
            context_node, score_copy = copy_from_node_attention(query_copy, ext_node_words, ext_node_reps, ext_node_words,
                                                                mem_mask=all_node_mask.unsqueeze(-2), v=self._attn_copyv)
`
it shows:
`
ext_info is None
`

**Comment by luyang-huang96** [comment]
Hi, 
copy_from_node =False should be set. This enables model to only copy from graph words, which hurts the performance

**Comment by yuezhao-zy** [comment]
> Hi,
> copy_from_node =False should be set. This enables model to only copy from graph words, which hurts the performance

ok, thanks!
