### ISSUE TITLE
no file in acl2020_clozedata_cnn/training

### ISSUE THREAD

**Issue by yuezhao-zy** [luyang-huang96/GraphAugmentedSum#2]
there is no file in acl2020_clozedata_cnn/training, which is needed in train_roberta_multiple_choice.py

**Comment by luyang-huang96** [comment]
Hi, please check readme file. I have posted data/model/results link there. please download them and change the folder name to adapt your usage. thanks!

**Comment by luyang-huang96** [comment]
You can also find align dictionary in 
I. our processed data with constructed graphs can be found here:
https://drive.google.com/open?id=1ccja3oyWIJIm91EiG-NJPFNb4Eg1pOmO

**Comment by Toni-Chan** [comment]
What are the aligned dictionary for?
