### ISSUE TITLE
No such file or directory: '/data2/luyang/process-nyt/bert_tokenizaiton_aligns/robertaalign-base-cased.pkl'

### ISSUE THREAD

**Issue by yuezhao-zy** [luyang-huang96/GraphAugmentedSum#3]
in  decoding.py", line 279,  error happens:
 
`   in __init__
 with open('/data2/luyang/process-nyt/bert_tokenizaiton_aligns/robertaalign-base-cased.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data2/luyang/process-nyt/bert_tokenizaiton_aligns/robertaalign-base-cased.pkl'`

could you explain what the robertalign-base-cased.pkl is used for? Thank!

**Comment by luyang-huang96** [comment]
#2

**Comment by WSChange** [comment]
> #2

Can you share file again? When I pick the edge,it just sad 404.
