### ISSUE TITLE
code for process data

### ISSUE THREAD

**Issue by yuezhao-zy** [luyang-huang96/GraphAugmentedSum#4]
Hi. Your job is very good!  Could you share your code to process data with constructed graphs because I want to apply the work to my own dataset. Thank you very much!

**Comment by luyang-huang96** [comment]
Hi Yuezhao,

I need some time to find scripts/codes for processing data. Could you please share your email here? I can email you when I'm ready.

Thank you!

**Comment by yuezhao-zy** [comment]
> Hi Yuezhao,
> 
> I need some time to find scripts/codes for processing data. Could you please share your email here? I can email you when I'm ready.
> 
> Thank you!

yuezhao_@outlook.com. Thanks again!

**Comment by yeliu918** [comment]
Hi luyang,

Thanks for the great job. Could you also share me the codes for processing? liuye.neu@gmail.com

Best,
Ye

**Comment by pingzhuu** [comment]
> Hi Yuezhao,
> 
> I need some time to find scripts/codes for processing data. Could you please share your email here? I can email you when I'm ready.
> 
> Thank you!

Hi Luyang, your job is great! Could you also share me the codes for processing data? Thanks! pingzhuu@outlook.com

**Comment by luyang-huang96** [comment]
Hi all,

I update scripts for processing data here: https://github.com/luyang-huang96/GraphAugmentedSum/tree/master/preprocess

Hope it is useful to your research!
